baseURL = "https://imod.bot/blog/"
canonifyURLs = true
languageCode = "en-us"
title = "Enum Blog"
theme = "lightbi-hugo-master"
[Params]
pagination = "10"

[Author]
  name = "KM, founder of Enum"
  website = "https://enumhq.com/"
